LIB_NAME := ./lib_emulator.a

all:
	# cat ../emulator_lib/${LIB_NAME}
	g++ ${CFLAGS} -o demo ./main.cpp ../emulator_lib/${LIB_NAME} 
	echo -e "\033[0;32m[MAKE] Demo application Compiled Succesfully"
	
